第11回課題提出（１）
shipo3/DateCalculation pull request #2
Opened 2022-06-17 10:15 UTC by shipo3

お世話になっております。
日付計算アプリにJunit5のテストコードを追加致しました。
Mapperクラス、Serviceクラスのテストを記載しております。
（*Controllerクラスは作成途中です。）

H2DBが使えていないのか？テスト自体はMapperクラスの「新規登録」以外はエラーとなっております。
2日ほどいろいろ試しましたが、DB問題は解消しない為
一度、テスト自体の記載方法は問題がないかをご確認いただいてもよろしいでしょうか？

お忙しいところ恐縮ですが
お手すきの際に、ご確認の程よろしくお願い致します。

2022-06-17 10:37 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/DateCalculationServiceTest.java
> +    void testDateAdjust(String inputDate) {
これがどういう目的のテストなのか書いてほしいです。
メソッド名日本語にできるのでそれでよいかなと。

テストケースの書き方はGiven-When-Thenなどで調べてみるとよいです。
※ゆーだいさんが昔まとめていた記事があるはずなので聞いてみてください！

2022-06-17 10:37 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/DateCalculationServiceTest.java
> +//    }
この辺は意図して残していますか？

2022-06-17 10:37 UTC, yoshi-koyama commented on src/test/java/com/example/demo/repository/DateCalculationMapperTest.java
> +	FormulaData formula = createFormula(4, "年と月", "最小値", -100, -100, 0);
ケース間で依存しないようにしましょう。
削除後に対象のデータが取得できなくなっていることを確認するようにしましょう。

2022-06-17 15:16 UTC, YudaiNoda3576 requested changes

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/DateCalculationServiceTest.java
> +    void testDateAdjust(String inputDate) {
テストケースの書き方はまとめてないですね。。。
ただこの記事は参考になるかと！Junitではないですが
https://applis.io/posts/how-to-create-test-cases

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +    void testGetFormulaData() throws Exception {
メソッド名を日本語にしている箇所と英語表記にしている箇所はどのような基準で区別されてますか？

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +    @DisplayName("パス指定で確認画面にアクセス時TOPに戻ること")
こちらのテストの目的は何ですかね？？
ケースと目的があってないような雰囲気を感じます

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +//    @Test
L73までのコメントアウトはどういった意図で残されてますか？？

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +//	.andExpect(model().attribute("complete", error))
こちらはテストが通らないからコメントアウトされてますか？？（もしそうならテストがテストとして成立していないか実装が誤っている可能性が高いです）

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/repository/DateCalculationMapperTest.java
> +	mapperTest.updateOne(4, "年と月", "最小値", -100, -100, 0);
こちらは全てのカラムの更新を確認しなくても良いかと思います。
一カラムだけ更新してその更新結果だけ検証すれば十分かと！

2022-06-17 15:16 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/repository/DateCalculationMapperTest.java
> +    public void 検索_1件して結果がキーに紐づく1件だけ取得出来る事() throws Exception {
IDに紐づくデータが存在するとき、一件取得できること
くらいでも良いかと思います！
またIDに紐づくデータが存在しないときのテストも必要になりそうです！

2022-06-18 03:27 UTC, shipo3 commented on src/test/java/com/example/demo/service/DateCalculationServiceTest.java
> +    void testDateAdjust(String inputDate) {
@yoshi-koyama @YudaiNoda3576 
ご指摘、情報いただきありがとうございます！
基本良く分からない状態で、下記を参考にして書いてみたという段階です・・・
https://oohira.github.io/junit5-doc-jp/user-guide/
https://www.udemy.com/course/java-junit5/learn/lecture/24219452?start=15#overview

メソッド名もJunit5だと英語なのか？と思ったりしてみたのですが
いただいた情報を元に再構築してみます！

2022-06-18 03:28 UTC, shipo3 commented on src/test/java/com/example/demo/service/DateCalculationServiceTest.java
> +//    }
成功例として残してました。削除します！

2022-06-18 03:29 UTC, shipo3 commented on src/test/java/com/example/demo/repository/DateCalculationMapperTest.java
> +	FormulaData formula = createFormula(4, "年と月", "最小値", -100, -100, 0);
承知致しました！　やってみます。

2022-06-18 03:30 UTC, shipo3 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +    void testGetFormulaData() throws Exception {
こういう書き方もあるのか。。どれが良いのかな。。と思っている段階です。
いただいたコメントによると、メソッド名を日本語にした方が良さそうです。

2022-06-18 03:33 UTC, shipo3 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +    @DisplayName("パス指定で確認画面にアクセス時TOPに戻ること")
全てのメソッドをテストしなくても問題ないでしょうか？
どういうテストをすべきなのか？考えてみます！

2022-06-18 03:40 UTC, shipo3 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +//	.andExpect(model().attribute("complete", error))
こちらも思考錯誤中です。恐縮です･･

2022-06-18 03:40 UTC, shipo3 commented on src/test/java/com/example/demo/controller/DateCalculationControllerTest.java
> +//    @Test
controllerも見ていただきまして恐縮です・・
これから中身を考えようと思っている部分です。
mainのメソッドを　ctrl+9　ですべてのメソッドの枠のみできた状態となっています。

2022-08-13 20:11 UTC, closed without merging